### ISSUE TITLE
gh actions update broke

### ISSUE THREAD

**Issue by matthewdeanmartin** [djh00t/klingon_tools#190]
I think this is the update you pushed in the last 24 hours

 File "C:\Users\matth\pipx\venvs\klingon-tools\Lib\site-packages\klingon_tools\logtools.py", line 154, in _log
    raise ValueError(
ValueError: Invalid style 'actions'. Valid styles are: default, pre-commit, basic, none

**Comment by matthewdeanmartin** [comment]
Specifically, this works:

`pipx install klingon-tools==2.1.1 --force`

`gh-actions-update --update`

But no later versions

**Comment by djh00t** [comment]
Hey thanks for reporting this.

That build has a few kinks to sort out. Do you have an example of how you're calling/using LogTools?

**Comment by matthewdeanmartin** [comment]
I'm not using the bundled logging library directly. `gh-actions-update` is using it or it is being imported (unnecessarily?) along the way. This is where splitting that into a separate app might be worth it. 

(WRT side projects, I got the same problem! with LLMs I can do so many side projects and it isn't clear in advance which parts will make more sense as stand alone)

**Comment by djh00t** [comment]
Yea the codebase sprawl is real. Thank you for prompting me to look at which features make sense to move into stand alone form and yes this entrypoint definitely qualifies.

I have a working version of the gh-actions-update on my laptop. Once I've finished tests to make sure it can't be broken again I will push it out. I should have it done tonight my time.

**Comment by matthewdeanmartin** [comment]
What is funny is that the bot wrote the app, and then the bot, using github as a "memory", recommended it to me

https://chatgpt.com/share/414c87d4-f2a3-4958-bdf6-a3559b378016

**Comment by djh00t** [comment]
Ha thats cool :) Glad to see my OpenAI dollars coming back to me.

In other news:
Publishing klingon_tools (2.1.5) to PyPI
 - Uploading klingon_tools-2.1.5-py3-none-any.whl 100%
 - Uploading klingon_tools-2.1.5.tar.gz 100%
 
You should have that entrypoint working again for you now. Let me know if you are still having issues. I migrated from setuptools to poetry recently but I'm pretty sure I've got tests covering most of those issues.

**Comment by matthewdeanmartin** [comment]
Works again, thanks!
